name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          brew update
          brew install gradle
          sudo gem install cocoapods

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build iOS Framework
        run: ./gradlew :shared:build

      - name: Build the iOS app
        run: |
          cd iosApp
          xcodebuild -project iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -configuration Debug
      

      - name: Archive iOS App
        run: |
          xcodebuild -project iosApp.xcodeproj -scheme iosApp -sdk iphoneos -configuration Release -archivePath $PWD/build/iosApp.xcarchive archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/iosApp.xcarchive -exportOptionsPlist iosApp/ExportOptions.plist -exportPath $PWD/build
