name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          brew update
          brew install gradle
          sudo gem install cocoapods

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build iOS Framework
        run: ./gradlew :shared:build

      - name: Build iOS App
        run: |
            cd iosApp
            xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/iosApp.xcarchive


      - name: Export IPA
        run: |
          cd iosApp
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>app-store</string><key>uploadBitcode</key><false/><key>compileBitcode</key><true/><key>signingStyle</key><string>manual</string><key>teamID</key><string>YOUR_TEAM_ID</string><key>provisioningProfiles</key><dict><key>YOUR_BUNDLE_IDENTIFIER</key><string>YOUR_PROVISIONING_PROFILE_NAME</string></dict></dict></plist>' > ExportOptions.plist
          xcodebuild -exportArchive -archivePath $PWD/build/iosApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
      

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
            name: ios-app
            path: iosApp/build/*.ipa